TaxRate M-M TaxCategory i
Lostmyname/solidus pull request #13
Opened 2017-04-20 12:51 UTC by vladstoick

2017-04-20 14:20 UTC, jordan-brough submitted a review, later dismissed
I left a few (belated) comments on #12, and one minor comment on the migration here.

This is great stuff!

2017-04-20 14:20 UTC, jordan-brough commented on core/db/migrate/20170412103617_transform_tax_rate_category_relation.rb
> +class TransformTaxRateCategoryRelation < ActiveRecord::Migration
For Solidus 2.0 you'll want to use `ActiveRecord::Migration[5.0]`

2017-04-21 12:47 UTC, jordan-brough requested changes
I left a few comments on things I didn't notice when I looked at the 1.4 version.  They're all minor though and if we want to make any changes I wouldn't worry about backporting them to 1.4 (unless you want to).

2017-04-21 12:47 UTC, jordan-brough commented on core/db/migrate/20170412103617_transform_tax_rate_category_relation.rb
> +      if tax_category_ids.count == 1
Not super important but just curious:  Do we need this special case?  The logic in the `else` would handle it right?  Is this just for readability?

2017-04-21 12:47 UTC, jordan-brough commented on core/app/models/spree/tax/tax_helpers.rb
> +        order_zone_tax_categories = rates_for_order_zone(order).flat_map(&:tax_categories)
We should probably add `.includes(:tax_categories)` to the scopes in `rates_for_order_zone` and `rates_for_default_zone` yeah?

2017-04-21 12:47 UTC, jordan-brough commented on core/app/models/spree/tax_category.rb
> +    has_many :tax_rate_tax_categories, class_name: Spree::TaxRateTaxCategory, dependent: :destroy
It would be good to add `inverse_of` here since I think that doesn't get added automatically to models in Solidus for some reason.

2017-04-21 12:47 UTC, jordan-brough commented on core/app/models/spree/tax_rate.rb
> +    has_many :tax_rate_tax_categories, class_name: Spree::TaxRateTaxCategory, dependent: :destroy
`inverse_of` here also

2017-04-21 12:47 UTC, jordan-brough commented on core/app/models/spree/tax_rate_tax_category.rb
> +    belongs_to :tax_rate, class_name: Spree::TaxRate
`inverse_of` here also

2017-04-21 12:47 UTC, jordan-brough commented on core/app/models/spree/tax_rate_tax_category.rb
> +    belongs_to :tax_category, class_name: Spree::TaxCategory
`inverse_of` here also

2017-04-21 13:18 UTC, vladstoick commented on core/db/migrate/20170412103617_transform_tax_rate_category_relation.rb
> +      if tax_category_ids.count == 1
yes that should be enough

2017-04-21 13:22 UTC, vladstoick commented on core/app/models/spree/tax/tax_helpers.rb
> +        order_zone_tax_categories = rates_for_order_zone(order).flat_map(&:tax_categories)
Yes I will add that as solidus 2.2 actually uses `rates_for_order(order).map(&:tax_category_id)`

2017-04-21 15:54 UTC, jordan-brough approved these changes
Looks great!

2017-04-24 08:08 UTC, merged